Repository freyxfi/BugRecon, pull requests merged in 2024-10, with the labels that each got.

#4 Create bug_recon.py
  bug_recon.py
Labels: Hacktoberfest, hacktoberfest-accepted, Code

#9 Mega add on test
  .github/workflows/python-app.yml
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#15 Site for Github Pages
  website/index.html
  website/styles.css
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted, Code, safe, testing, website

#17 Update bug_recon.py
  bug_recon.py
Labels: Code, hacker-mindset

#20 Added Contributors
  website/index.html
  website/styles.css
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#21 3 Level Recon
  bug_recon.py
Labels: Hacktoberfest, hacktoberfest-accepted, Code

#22 Created an API
  bugrecorn_server/README.md
  bugrecorn_server/app.py
Labels: Hacktoberfest, hacktoberfest-accepted, Code, testing, hacker-mindset

#26 Created Requirements file
  requirements.txt
Labels: Hacktoberfest, hacktoberfest-accepted
